### PR TITLE
add japanese readme

### PR DESCRIPTION
**Pull request by yamachan**
Add Japanese readme file.
Add a hyperlink to japanese readme on readme file.

### CODE REVIEW

**Comment by scottdangelo** [comment]
This is failing the Travis-ci tests.
Do you have the latest code from the Master branch? (i.e. have you done a `git pull` on the master branch?)
It might help to pass if you create your own branch with `git checkout -b <my_branch_name>` and then submit the pull request with that.
Looking at the previous commits, the tests were [passing](https://travis-ci.org/IBM/watson-vehicle-damage-analyzer/builds) , so I think the problem might be with this...But I'll check the credentials to verify

**Comment by scottdangelo** [comment]
I just tested another Pull request and it passed the tests. I think you need to get the latest code from master, and try to submit your new code on a branch.

**Comment by yamachan** [comment]
Hi @scottdangelo san, thank you for your test!

I had forked and updated this repo in a few hours, and as you can see in the detail, I had updated only 2 text (markdown) files, not updated any other codes or settings.

I'm not sure why my pull request has a problem...

**Comment by yamachan** [comment]
Hi @scottdangelo san,

I checked the Travis-CI log, and found the API access had a problem with id, pw, or API key. I guess that there was an access problem during [this build](https://travis-ci.org/IBM/watson-vehicle-damage-analyzer/jobs/413153597).

> **Line 887**
> Error: Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username/password, api_key, and iam_access_token.

Would you please do 'Restart build' for the build #161 of this pull request #59? I can't do so, because I don't have write access in this repo.

* [Trigger a Travis-CI rebuild without pushing a commit?](https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit)

**Comment by scottdangelo** [comment]
I did a restart, but I had already tried that and it is still failing.
Can you push your changes up on a branch, and I can try to upload them and see if there is a difference in how Travis CI tests?

**Comment by scottdangelo** [comment]
If you do a `git pull` on master, you should then be able to pass the tests. I think your version of the code is old.

**Comment by yamachan** [comment]
Hi @scottdangelo san,

Thanks!
I had forked this repo yesterday, so it's a mystery.

Anyway, there is something wrong with my fork or pull request.
I will close this pull request, and will try (from `git pull`) again.

**Pull request closed without merging**
